name: Renew Dev Orgs

on:
  schedule:
    - cron: "30 20 * * MON"   # every Monday, adjust if you like
  workflow_dispatch:

jobs:
  renew-dev-orgs:
    runs-on: ubuntu-latest
    environment: AFDevOrgRenew       # same environment that holds your secrets
    strategy:
      matrix:
        org: [AGENTFORCE_DEV_ORG_URL, LAGARDE_DEV_ORG_URL]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli -g

      # 🔑 Authenticate to the current org in the matrix
      - name: Authenticate ${{ matrix.org }}
        env:
          AUTH: ${{ secrets[matrix.org] }}
        run: |
          echo "$AUTH" > ./auth.txt
          sf org login sfdx-url -f ./auth.txt -a ${{ matrix.org }} -d

      # 🏷️ Do something trivial so the login counts
      - name: Touch the org
        run: sf data query -q "SELECT Name FROM Organization" -o ${{ matrix.org }}
